# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-18 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200418_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brief_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='full_description',
            field=models.TextField(null=True),
        ),
    ]
