# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-25 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200418_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image4',
        ),
        migrations.AlterField(
            model_name='product',
            name='catagory',
            field=models.CharField(choices=[('Workshop', 'Workshop'), ('Accessories', 'Accessories'), ('Components', 'Components'), ('Nutrition', 'Nutrition'), ('Clearance', 'Clearance')], max_length=254),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcatagory',
            field=models.CharField(choices=[('electronics', 'electronics'), ('bottles', 'bottles'), ('seat', 'seat'), ('helmet', 'helmet'), ('lights', 'lights'), ('locks', 'locks'), ('brakes', 'brakes'), ('drivechain', 'drivechain'), ('tyers', 'tyers'), ('wheels', 'wheels'), ('energyfood', 'energyfood'), ('energydrink', 'energydrink'), ('tools', 'tools'), ('lubricants', 'lubricants')], max_length=254),
        ),
    ]
