# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-25 12:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200425_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brief_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='full_description',
        ),
    ]
